import type { FastifyPluginAsync } from "fastify";

export const privacyPolicyLastUpdated = "September 1, 2026";

export function privacyPolicyHTML() {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="description" content="SubWise Privacy Policy — how the subscription discovery and savings app handles account, subscription, financial, and AI data.">
  <meta name="color-scheme" content="light dark">
  <title>Privacy Policy — SubWise</title>
  <style>
    :root{--ink:#10231d;--muted:#5f7069;--line:#dce7e2;--paper:#fff;--wash:#f4f8f6;--mint:#dff7eb;--green:#0d9960;--blue:#4389c8;--shadow:0 18px 50px rgba(15,45,34,.09)}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:radial-gradient(circle at 10% 0%,#ddf5e9 0,transparent 28rem),var(--wash);color:var(--ink);font:16px/1.65 -apple-system,BlinkMacSystemFont,"SF Pro Text",Inter,Segoe UI,sans-serif}
    a{color:#08764a;text-underline-offset:3px}a:hover{color:#064f34}.shell{width:min(1120px,calc(100% - 32px));margin:auto}.topbar{display:flex;align-items:center;justify-content:space-between;padding:24px 0}.brand{display:flex;align-items:center;gap:11px;color:var(--ink);text-decoration:none;font-weight:780;letter-spacing:-.02em}.mark{display:grid;place-items:center;width:38px;height:38px;border-radius:12px;background:var(--ink);color:#fff;box-shadow:0 8px 18px rgba(16,35,29,.18)}.status{padding:7px 12px;border:1px solid #b9ddcd;border-radius:999px;background:rgba(255,255,255,.7);color:#247253;font-size:13px;font-weight:650}
    .hero{padding:66px 0 46px}.eyebrow{display:inline-flex;gap:8px;align-items:center;color:var(--green);font-size:13px;font-weight:760;text-transform:uppercase;letter-spacing:.1em}.dot{width:8px;height:8px;border-radius:50%;background:var(--green)}h1{max-width:780px;margin:14px 0 18px;font-size:clamp(44px,8vw,78px);line-height:.98;letter-spacing:-.065em}.lead{max-width:720px;margin:0;color:var(--muted);font-size:clamp(18px,2.3vw,22px);line-height:1.5}.updated{margin-top:24px;color:var(--muted);font-size:14px}
    .layout{display:grid;grid-template-columns:250px minmax(0,1fr);gap:36px;align-items:start;padding-bottom:80px}.toc{position:sticky;top:20px;padding:20px;background:rgba(255,255,255,.72);border:1px solid var(--line);border-radius:22px;backdrop-filter:blur(16px)}.toc strong{display:block;margin-bottom:10px;font-size:14px}.toc a{display:block;padding:6px 0;color:var(--muted);font-size:14px;text-decoration:none}.toc a:hover{color:var(--green)}
    main{min-width:0;background:var(--paper);border:1px solid var(--line);border-radius:30px;box-shadow:var(--shadow);overflow:hidden}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:var(--line);border-bottom:1px solid var(--line)}.summary div{padding:24px;background:var(--paper)}.summary b{display:block;margin-bottom:7px;font-size:15px}.summary span{color:var(--muted);font-size:14px}.content{padding:clamp(26px,6vw,64px)}section{scroll-margin-top:24px;padding:10px 0 34px;border-bottom:1px solid var(--line)}section:last-child{border:0;padding-bottom:0}h2{margin:24px 0 10px;font-size:28px;line-height:1.2;letter-spacing:-.035em}h3{margin:24px 0 6px;font-size:18px}p{margin:8px 0 14px;color:#31433c}ul{padding-left:22px;color:#31433c}li{margin:8px 0}.note{margin:20px 0;padding:18px 20px;border-left:4px solid var(--green);border-radius:0 16px 16px 0;background:var(--mint)}.processor-list{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin-top:18px}.processor{padding:18px;border:1px solid var(--line);border-radius:17px}.processor b{display:block}.processor span{display:block;margin-top:4px;color:var(--muted);font-size:14px}.processor a{font-size:13px}
    footer{display:flex;justify-content:space-between;gap:20px;padding:26px 0 44px;color:var(--muted);font-size:13px}@media(max-width:800px){.layout{grid-template-columns:1fr}.toc{position:static}.summary{grid-template-columns:1fr}.processor-list{grid-template-columns:1fr}.hero{padding-top:36px}.status{display:none}}@media(prefers-color-scheme:dark){:root{--ink:#edf8f3;--muted:#a5b8b0;--line:#294239;--paper:#10231d;--wash:#091712;--mint:#153b2d;--green:#57d69a;--shadow:none}body{background:radial-gradient(circle at 10% 0%,#173b2e 0,transparent 28rem),var(--wash)}.mark{background:#e6f6ef;color:#10231d}.status,.toc{background:rgba(16,35,29,.78)}p,ul{color:#d4e1dc}.summary div{background:var(--paper)}a{color:#6ee2aa}a:hover{color:#a5f2cd}}@media print{body{background:#fff}.topbar,.toc,footer{display:none}.shell{width:100%}.hero{padding:20px 0}.layout{display:block}main{border:0;box-shadow:none}.content{padding:20px}}
  </style>
</head>
<body>
  <div class="shell">
    <header class="topbar"><a class="brand" href="/privacy-policy" aria-label="SubWise privacy policy home"><span class="mark" aria-hidden="true">S</span><span>SubWise</span></a><span class="status">Privacy-first by design</span></header>
    <div class="hero"><span class="eyebrow"><span class="dot"></span>Legal &amp; privacy</span><h1>Your subscriptions.<br>Your control.</h1><p class="lead">This policy explains what SubWise processes when it finds subscriptions, builds savings suggestions, or connects the services you choose.</p><p class="updated">Last updated: ${privacyPolicyLastUpdated}</p></div>
    <div class="layout">
      <nav class="toc" aria-label="Privacy policy sections"><strong>On this page</strong><a href="#scope">Scope</a><a href="#collect">Information we process</a><a href="#use">How we use it</a><a href="#share">When data is shared</a><a href="#choices">Your choices</a><a href="#retention">Retention &amp; deletion</a><a href="#security">Security</a><a href="#children">Children</a><a href="#international">International users</a><a href="#changes">Changes</a><a href="#contact">Contact</a></nav>
      <main>
        <div class="summary"><div><b>No credential access</b><span>SubWise never receives your bank password or Apple Account password.</span></div><div><b>No data sales</b><span>We do not sell personal data or use financial data for advertising.</span></div><div><b>You approve results</b><span>Detected subscriptions require confirmation before they are saved.</span></div></div>
        <div class="content">
          <section id="scope"><h2>1. Scope</h2><p>This Privacy Policy applies to the SubWise iOS application and the SubWise API and website. “SubWise,” “we,” and “us” refer to the developer and operator of the SubWise service.</p><p>SubWise helps people identify recurring charges, organize subscriptions, predict upcoming payments, and evaluate possible savings. It does not automatically cancel or change a subscription, and it does not provide banking, investment, tax, or legal advice.</p><div class="note"><strong>Offline mode:</strong> If you continue without an account, subscription records and preferences remain in the app’s local storage on your device unless you deliberately connect an online feature.</div></section>
          <section id="collect"><h2>2. Information we process</h2>
            <h3>Account and authentication data</h3><p>When you use Sign in with Apple, we receive an Apple-specific account identifier and, only when Apple makes them available and you choose to share them, your name and email address. We store protected session records so you can remain signed in. We do not receive your Apple Account password.</p>
            <h3>Subscription and savings data</h3><p>We process the information you enter or confirm, such as service and plan names, price, billing cycle, renewal or trial date, category, payment-method label, usage or importance choices, savings goals, recommendations, and actions you mark complete.</p>
            <h3>Bank and card connections through Plaid</h3><p>If you choose Connect account, Plaid connects to your financial institution. SubWise receives a provider token—not your bank password—and encrypts that token on the server. We process transaction descriptions, dates, amounts, recurrence information, institution names, and limited account labels to identify possible subscriptions. A detected item is not saved as your subscription until you confirm it. SubWise is designed as a subscription detector, not a complete transaction ledger.</p>
            <h3>Apple Wallet and screenshot discovery</h3><p>When available and authorized, FinanceKit lets the app read transactions from eligible accounts and date ranges you approve, or only transactions you choose manually. Wallet transactions are analyzed on your device, and only subscription details you confirm are saved locally. FinanceKit availability depends on country and account eligibility. Screenshot text recognition also runs on your device using Apple Vision; the selected screenshot is not uploaded to the SubWise API for OCR.</p>
            <h3>Savings Agent conversations</h3><p>If you enable and use the Savings Agent, SubWise sends your question and a structured summary of relevant subscriptions to the authenticated API and then to OpenAI to generate a response. Conversation messages and responses are stored so chat history works. We exclude bank credentials, access tokens, account numbers, and raw transaction histories from AI requests.</p>
            <h3>Household, notification, and device data</h3><p>Household features may store a household name, member display name, invitation email, signed invitation status, and the sharing level selected by the household. When server email delivery is enabled, the recipient address and invitation content are sent to our transactional email provider. Renewal notifications are scheduled locally. An APNs device token may be stored securely in the device Keychain for notification registration; the current service does not upload that token to the SubWise API.</p>
            <h3>Technical data</h3><p>Our hosting systems may process IP address, request time, request identifier, endpoint, response status, device or network metadata, and error details for security, abuse prevention, reliability, and troubleshooting. The iOS analytics abstraction filters merchant, amount, email, account, and token fields from local diagnostic events.</p>
          </section>
          <section id="use"><h2>3. How we use information</h2><ul><li>Authenticate accounts and keep data separated by user.</li><li>Detect recurring charges and normalize merchant names.</li><li>Calculate monthly and annual spending using confirmed prices.</li><li>Predict renewal timing and provide reminders.</li><li>Identify possible duplicates, price changes, and savings opportunities.</li><li>Provide household sharing according to the selected visibility level.</li><li>Operate the Savings Agent and retain conversation history.</li><li>Secure, monitor, debug, and improve the service.</li><li>Comply with applicable law and valid legal requests.</li></ul><p>We do not use financial data for behavioral advertising, and we do not sell personal information.</p></section>
          <section id="share"><h2>4. When data is shared</h2><p>We disclose data only as needed to operate a feature you request, protect the service, comply with law, or complete a business transition subject to appropriate safeguards.</p><div class="processor-list">
            <div class="processor"><b>Apple</b><span>Sign in with Apple, StoreKit, FinanceKit, Vision, and notification services.</span><a href="https://www.apple.com/legal/privacy/" rel="noopener noreferrer">Apple privacy</a></div>
            <div class="processor"><b>Plaid</b><span>Optional bank and card connection and recurring-transaction data.</span><a href="https://plaid.com/legal/#end-user-privacy-policy" rel="noopener noreferrer">Plaid privacy</a></div>
            <div class="processor"><b>OpenAI</b><span>Optional Savings Agent questions and structured subscription context.</span><a href="https://openai.com/policies/privacy-policy/" rel="noopener noreferrer">OpenAI privacy</a></div>
            <div class="processor"><b>Vercel</b><span>API hosting, networking, security, and operational logs.</span><a href="https://vercel.com/legal/privacy-notice" rel="noopener noreferrer">Vercel privacy</a></div>
            <div class="processor"><b>Neon</b><span>Encrypted-in-transit PostgreSQL database hosting for account data.</span><a href="https://neon.com/privacy-policy" rel="noopener noreferrer">Neon privacy</a></div>
            <div class="processor"><b>Resend</b><span>Transactional delivery of household invitation emails when server email is enabled.</span><a href="https://resend.com/legal/privacy-policy" rel="noopener noreferrer">Resend privacy</a></div>
            <div class="processor"><b>Household members</b><span>Only the service visibility you choose; never bank credentials or raw transaction descriptions.</span></div>
          </div></section>
          <section id="choices"><h2>5. Your choices and controls</h2><ul><li>Use offline mode without creating a SubWise server account.</li><li>Decline or revoke Apple Wallet, photo-library, or notification permissions in iOS Settings.</li><li>Choose which detected subscription candidates to add, edit, or ignore.</li><li>Disconnect a financial institution through SubWise support and manage Plaid connections through Plaid Portal where available.</li><li>Turn Savings Agent processing off in SubWise settings.</li><li>Control household visibility and remove household members.</li><li>Export the subscription records stored on your device as CSV.</li><li>Request access, correction, deletion, restriction, or portability where applicable.</li></ul><p>Some functionality will not work after you revoke required access, but bank connection and AI processing are always optional.</p></section>
          <section id="retention"><h2>6. Retention and deletion</h2><p>Local app data remains until you delete it, reset the app, or remove the app from your device. Server account data is retained while your account is active and deleted when the authenticated account-deletion process is completed, subject to limited legal, fraud-prevention, security, backup, and dispute-resolution needs. Deletion cascades through server subscriptions, sessions, institution connections, household records you own, savings plans, and AI conversations. Security audit records may remain after their direct account link is removed.</p><p>Plaid, Apple, OpenAI, Vercel, and Neon apply their own retention rules when acting as independent providers or subprocessors. You may also need to make a separate request to a provider, such as Plaid, for data controlled by that provider.</p></section>
          <section id="security"><h2>7. Security</h2><p>SubWise uses encrypted transport, authenticated user boundaries, hashed refresh tokens, Keychain storage for device credentials, encrypted Plaid access tokens, secret storage outside the iOS binary, request validation, rate limits, and logging redaction. No storage or transmission method can be guaranteed completely secure. Please report suspected unauthorized access through the contact channel below.</p></section>
          <section id="children"><h2>8. Children</h2><p>SubWise is intended for people who can lawfully manage financial accounts and subscriptions. It is not directed to children under 13, and we do not knowingly collect personal information from children under 13. If you believe a child has provided data, contact us so we can investigate and delete it where appropriate.</p></section>
          <section id="international"><h2>9. International users</h2><p>SubWise’s providers may process data in the United States and other countries. Privacy protections and government access rules can differ from those in your location. Depending on where you live, you may have rights to access, correct, delete, obtain, restrict, or object to processing of personal information, withdraw consent, or complain to a data protection authority.</p></section>
          <section id="changes"><h2>10. Changes to this policy</h2><p>We may update this policy as SubWise features, providers, or legal requirements change. We will post the revised policy here and update the date at the top. Material changes may also be presented in the app where appropriate.</p></section>
          <section id="contact"><h2>11. Contact</h2><p>For privacy questions, data-rights requests, or account deletion assistance, use the developer support contact on the SubWise App Store product page. To protect your data, we may need to verify that a request comes from the account holder.</p><p><strong>App:</strong> SubWise<br><strong>Bundle identifier:</strong> com.toto.Subwise<br><strong>Policy URL:</strong> <a href="https://subwise-api.vercel.app/privacy-policy">https://subwise-api.vercel.app/privacy-policy</a></p></section>
        </div>
      </main>
    </div>
    <footer><span>© 2026 SubWise</span><span>This page uses no advertising cookies or third-party analytics.</span></footer>
  </div>
</body>
</html>`;
}

const plugin: FastifyPluginAsync = async (app) => {
  app.get("/privacy", async (_request, reply) => reply.redirect("/privacy-policy", 308));
  app.get("/privacy-policy", async (_request, reply) => reply
    .header("Cache-Control", "public, max-age=3600, stale-while-revalidate=86400")
    .header("Content-Language", "en")
    .type("text/html; charset=utf-8")
    .send(privacyPolicyHTML()));
};

export default plugin;
